### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by XvaleX10** [Elephant1214/PaperFixes#7]
[latest.log](https://github.com/user-attachments/files/16470346/latest.log)

**Comment by Elephant1214** [comment]
Do you have either Just Enough IDs or Roughly Enough IDs? I know about the issue with it but haven't gotten to it, if so.

**Comment by XvaleX10** [comment]
> Do you have either Just Enough IDs or Roughly Enough IDs? I know about the issue with it but haven't gotten to it, if so.

I have the latest version of Roughly Enough IDs

**Comment by iLLHunter** [comment]
I am glad to hear you know what the issue is. I was not able to obtain helpful information. I get a crash using 1.2.0 version, just exit code 1, no crash report generated. 
If I take that .jar out the pack launches, if I use version 1.1.0 of the mod the pack launches. This is all I know. 

Using the older version of the mod is a work around. No urgency on the fix, just here to report. 

This is current mod list
<details>
!mixinbooter-7.1.jar
ActuallyAdditions-1.12.2-r152.jar
AdditionalEnchantedMiner-1.12.2-12.5.1.jar
Advanced+Machines-61.0.1.jar
AdvMachinesPatch-1.1.jar
ae2-uel-v0.56.6.jar
ae2stuff-0.7.0.4-mc1.12.2.jar
AE2WTLib-1.12.2-1.0.34.jar
aether_ii-1.12.2-0.3.0+build411-universal.jar
AkashicTome-1.2-12.jar
Apotheosis-1.12.2-1.12.5.jar
AppleSkin-mc1.12-1.0.14.jar
Aroma1997Core-1.12.2-2.0.0.2.b167.jar
Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar
astralsorcery-1.12.2-1.10.27.jar
AutoRegLib-1.3-32.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.12-mc1.12.2.jar
BetterSigns-1.0_v1.12.2.jar
BiblioCraft[v2.4.5][MC1.12.2].jar
BloodMagic-1.12.2-2.4.3-105.jar
Bookshelf-1.12.2-2.3.590.jar
branders-enhanced-mob-spawners-v1.12.2-1.4.4.jar.jar
BringMeTheRings-0.4.jar
buildcraft-all-7.99.24.8.jar
calculator-1.12.2-5.0.12-15.jar
CarbonConfig-1.12.2-1.2.4.jar
censoredasm5.20.jar
cfm-6.3.0-mc1.12.2.jar
ChickenChunks-1.12.2-2.4.2.74-universal.jar
Chisel-MC1.12.2-1.0.2.45.jar
Chunk-Pregenerator-1.12.2-4.4.9.jar
CleanView-1.12.2-v1c.jar
Clumps-3.1.2.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
CoFHCore-1.12.2-4.6.6.1-universal.jar
CoFHWorld-1.12.2-1.4.0.1-universal.jar
coherent_villages_beta_v1.4.10.jar
collective-1.12.2-3.0.jar
CommonCapabilities-1.12.2-2.4.8.jar
CompactSolars-1.12.2-5.0.18.341-universal.jar
ComputerCraft1.80pr1.jar
connectedglass-1.1.1-mc1.12.jar
Controlling-3.0.12.4.jar
CookingForBlockheads_1.12.2-6.5.0.jar
coroutil-1.12.1-1.2.37.jar
CraftTweaker2-1.12-4.1.20.655.jar
CTM-MC1.12.2-1.0.2.31 (1).jar
CustomStartingGear-1.12-1.2.0.9-universal.jar
CyclopsCore-1.12.2-1.6.7.jar
cyclopstek-1.0.34.jar
DimensionalDoors-1.12.2-3.1.2-UNOFFICIAL.jar
DynamicLights-1.12.2.jar
DynamicSurroundings-1.12.2-3.6.1.0.jar
dynviewdist-1.12-1.3.jar
ElectroblobsWizardry-4.3.14.jar
emt-12.4.5.jar
EnchantingPlus-1.12.2-5.0.176.jar
EnchantmentDescriptions-1.12.2-1.1.20.jar
EnderCompass-1.12.2-1.0.jar
EnderCore-1.12.2-0.5.76.jar
EnderIO-1.12.2-5.3.70.jar
EnderStorage-1.12.2-2.4.6.137-universal.jar
EnderTweaker-1.12.2-1.2.3.jar
EndReborn+[0.3.9].jar
energyconverters_1.12.2-1.3.7.30.jar
EngineersWorkshopReborn-1.12.2-1.0.9.40.jar
EntityCulling-1.12.2-6.4.3.jar
extraalchemy-forge-1.12-build11-0.5.4.jar
ExtraCells-1.12.2-2.6.5.jar
extrautils2-1.12-1.9.9.jar
ExtremeReactors-1.12.2-0.4.5.68.jar
Farseek-1.12-2.5.1.jar
farsight-1.6.jar
FlatBedrock-1.4.0_1.12.jar
FloodLights-1.12.2-1.4.4-22.jar
forbidden_arcanus-1.12.2-1.1.4.jar
Forgelin-1.8.4.jar
ForgeMultipart-1.12.2-2.6.2.83-universal.jar
FriendlyFire-1.12.2-1.5.10.jar
FTB-OdysseyWorld-1.12.2-1.1.0.11.jar
ftb-ultimine-1202.3.5.jar
Future-MC-0.2.20.jar
gaspunk-1.12.2-1.4.8.jar
GravelMiner_1.12.1-6.1.2.jar
Growable+Cells-1.12.2-3.1.0.jar
Guide-API-1.12-2.1.8-63.jar
GunpowderLib-1.12.2-1.1.jar
Hwyla-1.8.26-B41_1.12.2.jar
ic2-tweaker-0.2.1+build.4.jar
ImmersiveEngineering-0.12-98.jar
industrialcraft-2-2.8.222-ex112.jar
industrialforegoing-1.12.2-1.12.13-237.jar
IndustrialWires-1.7-36.jar
InfernalMobs-1.12.2.jar
IntegratedDynamics-1.12.2-1.1.11.jar
IntegratedTunnels-1.12.2-1.6.14.jar
IntegrationForegoing-1.12.2-1.11.jar
inventorysorter-1.12.2-1.13.3+57.jar
IronBackpacks-1.12.2-3.0.8-12.jar
ironchest-1.12.2-7.0.72.847.jar
ironfurnaces-1.3.5.jar
jei_1.12.2-4.16.1.301.jar
JERI-1.12.2-1.1.2.jar
justenoughdimensions-1.12.2-1.6.0-dev.20211009.214847.jar
KubeJS-forge-1.12.2-1.1.0.65.jar
landmines-1.0.1-mc1.12.jar
levelhearts-1.12.2-2.2.0.jar
LibVulpes-1.12.2-0.4.2-83-universal.jar
Locks-1.12.2-3.0.0.jar
logisticspipes-0.10.4.5.jar
lostcities-1.12-2.0.22.jar
magicalcrops-1.0.2-MC-1.12.jar
magicalcropsfix1.0.jar
malisiscore-1.12.2-6.5.1.jar
malisisdoors-1.12.2-7.3.0.jar
Mantle-1.12-1.3.3.55.jar
materialchanger1.0.3-1.12.2.jar
materialis-1.12.2-1.2.5.jar
MatterOverdrive-1.12.2-0.7.1.0-universal.jar
mcjtylib-1.12-3.5.4.jar
Mekanism-1.12.2-9.8.3.390.jar
MekanismGenerators-1.12.2-9.8.3.390.jar
MekanismTools-1.12.2-9.8.3.390.jar
minerva-library-1.0.13.jar
ModularPowersuits-1.12.2-1.1.048.jar
movingelevators-1.2.34-mc1.12.jar
MPUtils-1.12.2-1.5.7.jar
MrTJPCore-1.12.2-2.1.4.43-universal.jar
MultithreadedNoise-1.12.2-0.0.2.jar
mystcraft-1.12.2-0.13.7.06.jar
NaturesCompass-1.12.2-1.8.5.jar
Netherending-Ores-1.12.2-1.4.2.jar
NoFog-1.12.2b3.jar
NotEnoughItems-1.12.2-2.4.3.245-universal.jar
Nothirium-1.12.2-0.3.4-beta.jar
Numina-1.12.2-1.1.049.jar
Nyx-1.4.2.jar
OpenBlocks-1.12.2-1.8.1.jar
OpenComputers-MC1.12.2-1.7.5.192.jar
OpenModsLib-1.12.2-0.12.2.jar
OptiFine_1.12.2_HD_U_G5.jar
OreLib-1.12.2-3.6.0.1.jar
overloadedarmorbar-1.0.4g.jar
p455w0rdslib-1.12.2-2.3.161.jar
packedup-1.0.23-mc1.12.jar
PaperFixes-1.1.0.jar
Patchouli-1.0-23.6.jar
PerfectSpawn-MC1.12.2-2.1.jar
performant-1.11.jar
Placebo-1.12.2-1.6.0.jar
plustic-8.0.6.jar
portality-1.12.2-1.2.3-15.jar
PotionPlus-1.12.2.jar
ProjectE-1.12.2-PE1.4.1.jar
ProjectRed-1.12.2-4.9.4.120-Base.jar
ProjectRed-1.12.2-4.9.4.120-fabrication.jar
ProjectRed-1.12.2-4.9.4.120-integration.jar
ProjectRed-1.12.2-4.9.4.120-lighting.jar
ProjectRed-1.12.2-4.9.4.120-mechanical.jar
ProjectRed-1.12.2-4.9.4.120-world.jar
QuickLeafDecay-MC1.12.1-1.2.4.jar
randompatches-1.12.2-1.22.1.10.jar
randomportals-1.12.2-1.8.2.4.jar
randomtweaks-1.12.2-2.8.3.1.jar
ReachFix-1.12.2-1.0.10.jar
RebornCore-1.12.2-3.19.5-universal.jar
recycler-3.2.4-1.12.jar
redirectionor-1.7 for 1.12.2-1.8.8.jar
RedstoneArsenal-1.12.2-2.6.6.1-universal.jar
RedstoneFlux-1.12-2.1.1.1-universal.jar
refinedstorage-1.6.16.jar
refinedstorageaddons-0.4.5.jar
RenderLib-1.12.2-1.3.5.jar
rftools-1.12-7.73.jar
rftoolsctrl-1.12-2.0.2.jar
RPG-HUD-3.8.1.jar
secretroomsmod-1.12.2-5.6.4.jar
simpleteleporters-1.12.2-3.0.2.jar
SolarGeneration-1.12.2-1.3.0.jar
sonarcore-1.12.2-5.0.19-20.jar
spatialservermod-1.3.1.jar
Streams-1.12-0.4.9.jar
supermartijn642configlib-1.0.9-mc1.12.jar
supermartijn642corelib-1.0.12-mc1.12.jar
TConstruct-1.12.2-2.13.0.183.jar
TechReborn-1.12.2-2.27.3.1084-universal.jar
tesla-core-lib-1.12.2-1.0.17.jar
tesseract-1.0.21-mc1.12.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
ThaumicJEI-1.12.2-1.7.0.jar
ThermalCultivation-1.12.2-0.3.6.1-universal.jar
ThermalExpansion-1.12.2-5.5.7.1-universal.jar
ThermalFoundation-1.12.2-2.6.7.1-universal.jar
ThermalInnovation-1.12.2-0.3.6.1-universal.jar
torcherino-7.6.jar
trashcans-1.0.11-mc1.12.jar
tropicraft-MC1.12.2-7.1.9.115.jar
unloader-1.2.0.jar
vintagefix-0.5.1.jar
WaterStrainer-1.12-3.3.0.jar
Waystones_1.12.2-4.1.0.jar
WeatherConfig-1.12-1.0.1.jar
WirelessCraftingTerminal-1.12.2-3.12.97.jar
WirelessFluidTerminal-1.12.2-1.0.4.jar
WitherSkeletonTweaks-1.12.2-2.6.3.jar
worldedit-forge-mc1.12.2-6.1.10-dist.jar
XaerosWorldMap_1.39.0_Forge_1.12.jar
Xaeros_Minimap_21.15.0.1_Forge_1.12.jar
xray-1.12.2-1.6.0.jar
YARCF-0.14(1.12.2).jar
zerocore-1.12.2-0.1.2.9.jar
[___MixinCompat-1.1-1.12.2___].jar
</details>

**Comment by Elephant1214** [comment]
The mixins in 1.1.0 do not work at all iirc, 1.2.0 fixes that problem. 1.1.0 might with Mixin Booter but from memory it does not at all. I'll get to this tomorrow or Tuesday, I've been too busy with college, work, and other projects, but I should have some time in the next couple of days.
